import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { LoadingProvider } from "../contexts/LoadingContext";
import { AuthProvider } from "../contexts/AuthContext";
import { TimerProvider } from "../contexts/TimerContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-white text-gray-900 min-h-screen`}
      >
        <AuthProvider>
          <LoadingProvider>
            <TimerProvider>
              <div className="min-h-screen">{children}</div>
            </TimerProvider>
          </LoadingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
